//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "LineStations")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub line_id: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub station_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::rail_lines::Entity",
        from = "Column::LineId",
        to = "super::rail_lines::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    RailLines,
    #[sea_orm(
        belongs_to = "super::stations::Entity",
        from = "Column::StationId",
        to = "super::stations::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Stations,
}

impl Related<super::rail_lines::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RailLines.def()
    }
}

impl Related<super::stations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Stations.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
