//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "LineStation")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub line_id: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub station_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::rail_line::Entity",
        from = "Column::LineId",
        to = "super::rail_line::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    RailLine,
    #[sea_orm(
        belongs_to = "super::station::Entity",
        from = "Column::StationId",
        to = "super::station::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Station,
}

impl Related<super::rail_line::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RailLine.def()
    }
}

impl Related<super::station::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Station.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
