//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "RailLines")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, unique)]
    pub id: i32,
    #[sea_orm(unique)]
    pub name: String,
    pub red: i16,
    pub green: i16,
    pub blue: i16,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::line_stations::Entity")]
    LineStations,
}

impl Related<super::line_stations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LineStations.def()
    }
}

impl Related<super::stations::Entity> for Entity {
    fn to() -> RelationDef {
        super::line_stations::Relation::Stations.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::line_stations::Relation::RailLines.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
