//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "Stations")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, unique)]
    pub id: i32,
    #[sea_orm(unique)]
    pub name: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::line_stations::Entity")]
    LineStations,
    #[sea_orm(has_many = "super::user_stations::Entity")]
    UserStations,
}

impl Related<super::line_stations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LineStations.def()
    }
}

impl Related<super::user_stations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserStations.def()
    }
}

impl Related<super::rail_lines::Entity> for Entity {
    fn to() -> RelationDef {
        super::line_stations::Relation::RailLines.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::line_stations::Relation::Stations.def().rev())
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        super::user_stations::Relation::Users.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::user_stations::Relation::Stations.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
