//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "Station")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, unique)]
    pub id: i32,
    #[sea_orm(unique)]
    pub name: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::line_station::Entity")]
    LineStation,
    #[sea_orm(has_many = "super::user_station::Entity")]
    UserStation,
}

impl Related<super::line_station::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LineStation.def()
    }
}

impl Related<super::user_station::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserStation.def()
    }
}

impl Related<super::rail_line::Entity> for Entity {
    fn to() -> RelationDef {
        super::line_station::Relation::RailLine.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::line_station::Relation::Station.def().rev())
    }
}

impl Related<super::user::Entity> for Entity {
    fn to() -> RelationDef {
        super::user_station::Relation::User.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::user_station::Relation::Station.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
