//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "User")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, unique)]
    pub id: i32,
    #[sea_orm(unique)]
    pub email: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::user_station::Entity")]
    UserStation,
}

impl Related<super::user_station::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserStation.def()
    }
}

impl Related<super::station::Entity> for Entity {
    fn to() -> RelationDef {
        super::user_station::Relation::Station.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::user_station::Relation::User.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
